### ISSUE TITLE
Dynamic styles

### ISSUE THREAD

**Issue by dominykasgithub** [hunterliu1003/vue-final-modal#11]
Hi,

What do you think of adding to props `overlayStyle` and `contentStyle` ?
My use case would be having computed property in `contentStyle`.
Current workaround is creating for loop in sass having classes from `products-modal--top30` to `products-modal--top0`

**Comment by hunterliu1003** [comment]
Hi @dominykasgithub ,

Thanks for your feedback again.
> Current workaround is creating for loop in sass having classes from `products-modal--top30` to `products-modal--top0`

The workaround will generate large CSS content in final bundle.

**Comment by hunterliu1003** [comment]
The feature is released in 
- `v0.17.0` for Vue 2
- `v1.4.0` for Vue 3

**Comment by dominykasgithub** [comment]
thx!
