### ISSUE TITLE
The modal instance is not removed when the component is destroyed

### ISSUE THREAD

**Issue by Mini-ghost** [hunterliu1003/vue-final-modal#12]
### Versions

- vue-final-modal: 0.17.1

### Steps to reproduce

DEMO（Codepen）：https://codepen.io/mini_ghost/pen/vYKRoOv

1. In the demo.（please use "Debug mode" or "Full Page View"）
1. Close modal and change router to Page B, then Backe to Page A and repeat several times.
1. Then open devtool Console.

![image](https://user-images.githubusercontent.com/39984251/97783761-bd6d3680-1bd4-11eb-81ed-c0346bf55c48.png)

### What is Expected?

When user switch to Page B, modal's instance at Page A should be removed.

### What is actually happening?

The modal instance is not removed when the vue-final-modal component is destroyed

**Comment by hunterliu1003** [comment]
@Mini-ghost 

Thanks for your feedback.
The bugfix version is published to
- `v0.17.2` for Vue 2
- `v1.4.2` for Vue 3
