### ISSUE TITLE
Add support for Esc key to close the modals

### ISSUE THREAD

**Issue by WoodyDark** [hunterliu1003/vue-final-modal#13]
Pressing Esc key to close an active modal is a common accessibility feature. Would like to propose that pressing Esc key closes the top-most modal.

**Comment by hunterliu1003** [comment]
Hi @WoodyDark,

Thanks for your nice suggestion.
Now `vue-final-modal` support `Esc` key to close the modals.

- [`0.19.0`](https://www.npmjs.com/package/vue-final-modal/v/0.19.0) for Vue 2
- [`1.6.0`](https://www.npmjs.com/package/vue-final-modal/v/1.6.0) for Vue 3

Please checkout the documents for prop `escToClose`:
https://5fae4c79fa080b8b0998d68b--vue-final-modal.netlify.app/#esctoclose
