### ISSUE TITLE
[Bug] Closing any modal will cause the page scrollbar to reappear, even though there are still opened modals

### ISSUE THREAD

**Issue by WoodyDark** [hunterliu1003/vue-final-modal#14]
### Expected Behavior
Scrollbar only reappears when all the modals are closed.

### Current Behavior
Closing any modal will cause the page scrollbar to reappear, even though there are still opened modals

### Behavior Reproduction
https://codesandbox.io/s/happy-water-lpf5t

**Comment by hunterliu1003** [comment]
Hi @WoodyDark,

Thanks for your feedback.

The issue was fixed in
- v0.18.0 for Vue 2
- v1.5.0 for Vue 3

In addition, you have to replace

```
Vue.use(VueFinalModal)
```

to

```
Vue.use(VueFinalModal())
```

because of the new configuration.
Please checkout the docs:
https://vue-final-modal.org/#configuration
