### ISSUE TITLE
遮罩层应该用 fixed 比较好

### ISSUE THREAD

**Issue by gfd6th** [hunterliu1003/vue-final-modal#17]
https://github.com/hunterliu1003/vue-final-modal/blob/48a235044e51fd6e8a242bd69964110e6e9f5061/lib/VueFinalModal.vue#L8

参考https://segmentfault.com/q/1010000013961684
遮罩层应该用 fixed 比较好,
![Jietu20201109-131944](https://user-images.githubusercontent.com/6814715/98503474-93c8a500-228f-11eb-8748-d7d3439dac9c.jpg)
absolute可能会出现问题, 比如我就出现了上面的问题

**Comment by hunterliu1003** [comment]
如果使用 attach 的話，記得要在外層加上 `position: relative` 哦

```html
<vue-final-modal attach="#attach">
    ...some content
</vue-final-modal>

<div id="attach" style="position: relative">
    vue-final-modal is attached to here
</div>
```

**Comment by gfd6th** [comment]
试过了加 relative, 如果页面高度超过屏幕, 会出现在整个页面居中, 而不是当前屏幕 100vh 居中
![Jietu20201109-163539](https://user-images.githubusercontent.com/6814715/98517884-93d59e80-22a9-11eb-8b18-ab6723d98ded.jpg)
![Jietu20201109-163603](https://user-images.githubusercontent.com/6814715/98517895-9801bc00-22a9-11eb-9376-487d48c7558a.jpg)

**Comment by hunterliu1003** [comment]
有嘗試把 attach 拔掉嗎？
因為看你的情況應該不需要使用到 attach

**Comment by hunterliu1003** [comment]
預設情況 vue-final-modal 是使用 `fixed`，
attach 改用 `absolute` 的目的在於將 modal 限制在某特定 Dom element 之中。

**Comment by gfd6th** [comment]
不加 attach 确实可以, 之前我没留意我的 wrapper 上面使用了 space-x-8, 所以 attach的 dom append 到 wrapper 之后, 加上了一个 padding, 导致无法全屏遮罩, 所以我attach 到了 body 上面
