### ISSUE TITLE
Issue in npm install

### ISSUE THREAD

**Issue by shikharani16** [hunterliu1003/vue-final-modal#3]
Hi I was trying use this in my project.

I installed it by npm install.
Installation went fine. On npm run I am getting this  error

ERROR in ./node_modules/vue-final-modal/lib/VueFinalModal.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <div
|     v-if="ssr || visible"
 @ ./node_modules/vue-final-modal/lib/index.js 1:0-39 3:29-34
  @ ./index.js
   @ multi ./index.js

I just added
import { VueFinalModal } from 'vue-final-modal/lib' in my code and start getting this error.

Is there any prerequisite  for this..?

**Comment by hunterliu1003** [comment]
Hi @shikharani16 

> ERROR in ./node_modules/vue-final-modal/lib/VueFinalModal.vue 1:0
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

I guess this means thath Webpack don't know what to do with `.vue` file type.

1. Try add [vue-loader](https://vue-loader.vuejs.org/guide/) to your webpack config

> This might be the same issue https://forum.vuejs.org/t/app-vue-module-parse-failed-unexpected-token-1-0/54125

2. Try use umd build for you project:

```js
import { VueFinalModal } from 'vue-final-modal'

Vue.component('VueFinalModal', VueFinalModal)
```

**Comment by shikharani16** [comment]
HI ,
This error is gone . I did Step 2.
import { VueFinalModal } from 'vue-final-modal'
Vue.component('VueFinalModal', VueFinalModal)

Still It doesn't seems to be working.. It comes all over places. I think somehow  It is not able to Understand Css. I was following this https://codepen.io/hunterliu1003/pen/RwaQmo. We need to define classes for the size..? or w ecan mention height/ width somewhere.

**Comment by hunterliu1003** [comment]
Hi,

> Still It doesn't seems to be working.. It comes all over places. I think somehow It is not able to Understand Css. I was following this https://codepen.io/hunterliu1003/pen/RwaQmo. We need to define classes for the size..? or w ecan mention height/ width somewhere.

The codepen link above was broken.

Vue Final Modal was a renderless component, so you have to define all style by yourself.
I wrote an plain css example without using tailwindCSS
https://codepen.io/hunterliu1003/pen/ZEWoYeE

**Comment by shikharani16** [comment]
Hi,
I followed your example and It is working almost fine. I see a Overlap from last page on Modal Dialog.
So this needs to be handled by classes what we are providing..? For example  ( modal,modal-content ) in https://codepen.io/hunterliu1003/pen/ZEWoYeE .
I tried using z-index property of vue-final-modal but that doesn't seems to be working.
I am attaching the screenshot of my problem. The tab coming over Modal or of DOJO framework.
As we are partially migrating application to Vue.js
![image](https://user-images.githubusercontent.com/29137636/92910958-28f11e00-f446-11ea-9e16-e404edce8e6b.png)

**Comment by hunterliu1003** [comment]
Hi @shikharani16,

1.
> I followed your example and It is working almost fine. I see a Overlap from last page on Modal Dialog.
> So this needs to be handled by classes what we are providing..? For example ( modal,modal-content ) in https://codepen.io/hunterliu1003/pen/ZEWoYeE .

- You can use `overlay-class` property to overwrite the overlap style.
- If you don't want to display overlay, you can set `hide-overlay` property `true` to hide.

2.
> I tried using z-index property of vue-final-modal but that doesn't seems to be working.
> I am attaching the screenshot of my problem. The tab coming over Modal are of DOJO framework.
> As we are partially migrating application to Vue.js

There might be a lot of situations cause z-index not work.
You can try set `attach` property to `body`, and then the modal will be append to `body` element.

```html
<vue-final-modal attach="body">
    ...
</vue-final-modal>
```

**Comment by shikharani16** [comment]
Thank you very much for all the help It worked with  **set hide-overlay property true to hide.**
 It is looking all good
