### ISSUE TITLE
issue with prod build

### ISSUE THREAD

**Issue by shikharani16** [hunterliu1003/vue-final-modal#6]
**ERROR in vueBundle.js from UglifyJs
Unexpected token: keyword «const» [vueBundle.js:14019,6022]**
I am getting this error. I am using Webpack : 4 .I know this component is using  ES6 and UglifyJS does not support ES6.
Do you some suggestion what should I do to resolve it.

**Comment by hunterliu1003** [comment]
Hi @shikharani16,

I found this:

https://github.com/terser/terser#why-choose-terser:

```
Why choose terser?
uglify-es is no longer maintained and uglify-js does not support ES6+.

terser is a fork of uglify-es that mostly retains API and CLI compatibility with uglify-es and uglify-js@3.
```

Maybe you can replace `UglifyJs` with `terser-webpack-plugin`:

https://www.npmjs.com/package/terser-webpack-plugin

**Comment by shikharani16** [comment]
Hi,, yes I tried It yesterday and it was working fine. Thanks

**Comment by hunterliu1003** [comment]
Hi, @shikharani16 

I found the library build was not full compile to es5,
so I just publish version [`v0.13.5`](https://www.npmjs.com/package/vue-final-modal/v/0.13.5) to fixed this.

If you want to know, here is the commit d355657a00fa4793116ee398762e2a4d561c665b

**Comment by shikharani16** [comment]
sure will check and let you know. Thank you

**Comment by shikharani16** [comment]
Hi, I have updated  to release v0.13.5 and now look like new problem is coming after that.
I am stuck in show/hide. I am using v-model property to do show/hide from outside and inside the component.but may times it is  opening two Modal windows.

**Comment by hunterliu1003** [comment]
Hi,

You should update version to `0.15.0` for the new API.

here is the example:
https://codepen.io/hunterliu1003/pen/dyXyBpR

**Comment by shikharani16** [comment]
I tried using 0.15.0 but looks like that created many issues with CSS so I switched back to 0.13.5.
