### ISSUE TITLE
幾個許願

### ISSUE THREAD

**Issue by yuda-lyu** [hunterliu1003/vue-final-modal#7]
為開源同好獻上星星，另許願如下：

1.是否能加入點擊overlay時觸發事件
因我自己是喜愛vuetify的dialog，故想許願能於clickToClose=false時(點擊overlay不隱藏表單)，能有小動畫提示使用者。關於vuetify dialog是微振動一下(調整transform scale)，故主要是許願有點擊overlay事件，方能添加此類動畫效果，而before-close事件是clickToClose=true才會觸發。

2.是否能新增slot相關範例
建議docs中關於slot功能處多給幾個範例，也給個多層modal的範例。多層這範例您主要是放在「8. Make the modal stackable」，我這邊是因於SPA常用到dialog，故許願希望slot教學處有明確範例能測試與複製code。

3.是否能替換隱藏body scroll方式
因開啟dialog會讓body捲軸隱藏(body-scroll-lock)，這是常見方法，但此會導致原排版微調，若原頁面存在高耗之表格或繪圖組件，會導致額外渲染開銷，故許願能於overlay層屏蔽捲動、拖曳(drag)、touch事件作為替代。

4.是否能加入鎖定駐點於dialog內之無障礙功能
熱鍵tab時會切到dialog背後的按鈕等有駐點元素，對於使用閱讀器的使用者較為困擾。焦點問題可參考：
https://developers.google.com/web/fundamentals/accessibility/focus/using-tabindex?hl=zh-tw
https://www.cntofu.com/book/189/posts/a11y-focus.md

**Comment by hunterliu1003** [comment]
Hi @yuda-lyu,

感謝你給的這些建議，我逐項回覆一下：

> 1.是否能加入點擊overlay時觸發事件

 
> 2.是否能新增slot相關範例


> 3.是否能替換隱藏body scroll方式

> 4.是否能加入鎖定駐點於dialog內之無障礙功能

**Comment by hunterliu1003** [comment]
Hi @yuda-lyu,

我逐項回覆一下：

> 1.是否能加入點擊 overlay 時觸發事件

可以，Vuetify dialog (點擊 overlay 不隱藏表單) 的動畫提示我也覺得很棒，會提供事件方便客製化，並補上範例。

> 2.是否能新增 slot 相關範例

感謝建議，之後會不斷新增更多更多更多的範例。

> 3.是否能替換隱藏 body scroll 方式

原本沒想到會有額外的渲染開銷，改用 `於 overlay 層屏蔽捲動、拖曳(drag)、touch事件作為替代` 可能會是個更好的方法，我會嘗試看看。

> 4.是否能加入鎖定駐點於 dialog 內之無障礙功能

感謝提供資訊，我會研究一下看看怎麼加入無障礙功能，可能需要實作一個 focus trap。

**Comment by hunterliu1003** [comment]
Hi @yuda-lyu,

先回應第 3 點：

目前不會考慮使用 `於overlay層屏蔽捲動、拖曳(drag)、touch事件` 替代 `body-lock-scroll`，
如果遇到 `原頁面存在高耗之表格或繪圖組件，會導致額外渲染開銷` 這樣的狀況，可以設置 prop `:lockScroll="false"`，並自行實現 `屏蔽捲動` 功能。

另外 [v0.14.0](https://www.npmjs.com/package/vue-final-modal/v/0.14.0) 新增了：

1.加入事件 `@click-outside`，提供禁制點擊外部關閉動畫的彈性

2.移除無用的 slot 避免誤會 `content-before`, `content`, `content-after`

4.已新增範例，並支援無障礙功能，請參考 [文件和範例](https://vue-final-modal.org/examples#accessibility)

**Comment by hunterliu1003** [comment]
Hi @yuda-lyu,

經過一些研究之後 [v0.15.0](https://www.npmjs.com/package/vue-final-modal/v/0.15.0)，不再依賴 `body-lock-scroll` 了。
再次感謝你的回饋。
另外，這版也新增了 API 
- `$vfm.hide(name)`
- `$vfm.show(name)`
- `$vfm.toggle(name, show)`
- `$vfm.modals`
- `$vfm.openedModals`
- `$vfm.hideAll()`
