### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hunterliu1003** [hunterliu1003/vue-final-modal#8]
- [ ] Draggable
- [ ] Resizable
- [ ] Themes for other UI frameworks like BootstrapVue, Vuetify, ElementUI, etc.

**Comment by hunterliu1003** [comment]
Move this to projects [Roadmap](https://github.com/hunterliu1003/vue-final-modal/projects/1).

**Comment by claudemangen** [comment]
Hello @hunterliu1003,

is it still planned to make the modal draggable and resizable?

Thank you very much.
